### ISSUE TITLE
Vaadin 8.0beta1 - Vaadin7 components from compatibility module not available

### ISSUE THREAD

**Issue by darkwitch** [mike-goetz/spring-boot-vaadin#1]
Since not all vaadin components are available on beta1 (most notably Tree, planned for Vaadin 8.1), there's a compatibility module available (vaadin-compatibility-server, vaadin-compatibility-client), but It is not used by this project.

**Comment by darkwitch** [comment]
Fixed in pull request #2

**Comment by mike-goetz** [comment]
Pull-Request integrated. Created a new branch to keep origin/master as clean as possible.
Intention of the project was to show how easy you can get started with Vaddin8 :)

Thanks anyways
